baseURL = "https://tecnologia.tole.es"
languageCode = "es-es"
title = "Los últimos descuentos detectados!"
theme = "hugo-shopping-product-catalogue-simple"

[Params]
description = "Las últimas rebajas de"
channel = "https://t.me/s/todotech"
ga = "G-05YE0XR7L3"
yandex = "3046232937495f92"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]