baseURL = "https://tecnologia.tole.es"
title = "Últimas ofertas en tecnología"
theme = "portfolio"
languageCode = "es-es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""


[sitemap]
  changefreq = "hourly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  copyright = ""
  sidebarAbout = []
  # Enable Google Analytics by entering your tracking code
  description = "Descuentazos en tecnología"
  gtag = "G-05YE0XR7L3"
  yandex = "3046232937495f92"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Raíz  "
  url = "/"
  home = true


  [outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
